vic:
  jwt:
    secret: Vic@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥,需保存好
    pubKeyPath: F:/IdeaProjects/spring-boot-demo/spring-boot-jjwt/rsa/rsa.pub # 公钥地址
    priKeyPath: F:/IdeaProjects/spring-boot-demo/spring-boot-jjwt/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: VIC_TOKEN